// ISO 3166-1 alpha-3 country codes as used by MyInvois.
// Source: https://sdk.myinvois.hasil.gov.my/codes/countries/
// Subset of the most commonly used codes. Extend as needed.
export const COUNTRY_CODES = {
  MYS: 'Malaysia',
  SGP: 'Singapore',
  IDN: 'Indonesia',
  THA: 'Thailand',
  VNM: 'Viet Nam',
  PHL: 'Philippines',
  BRN: 'Brunei Darussalam',
  KHM: 'Cambodia',
  LAO: 'Laos',
  MMR: 'Myanmar',
  CHN: 'China',
  HKG: 'Hong Kong',
  TWN: 'Taiwan',
  JPN: 'Japan',
  KOR: 'Korea, Republic of',
  IND: 'India',
  PAK: 'Pakistan',
  BGD: 'Bangladesh',
  LKA: 'Sri Lanka',
  USA: 'United States',
  CAN: 'Canada',
  GBR: 'United Kingdom',
  IRL: 'Ireland',
  FRA: 'France',
  DEU: 'Germany',
  ITA: 'Italy',
  ESP: 'Spain',
  NLD: 'Netherlands',
  BEL: 'Belgium',
  CHE: 'Switzerland',
  AUT: 'Austria',
  SWE: 'Sweden',
  NOR: 'Norway',
  DNK: 'Denmark',
  FIN: 'Finland',
  AUS: 'Australia',
  NZL: 'New Zealand',
  ARE: 'United Arab Emirates',
  SAU: 'Saudi Arabia',
  QAT: 'Qatar',
  KWT: 'Kuwait',
  OMN: 'Oman',
  BHR: 'Bahrain',
  EGY: 'Egypt',
  ZAF: 'South Africa',
  TUR: 'Turkey',
  RUS: 'Russian Federation',
  BRA: 'Brazil',
  MEX: 'Mexico',
} as const;

export type CountryCode = keyof typeof COUNTRY_CODES;
