export const CURRENCY_CODES = {
  MYR: 'Malaysian Ringgit',
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'Pound Sterling',
  SGD: 'Singapore Dollar',
  AUD: 'Australian Dollar',
  JPY: 'Japanese Yen',
  CNY: 'Chinese Yuan Renminbi',
  HKD: 'Hong Kong Dollar',
  TWD: 'New Taiwan Dollar',
  KRW: 'South Korean Won',
  INR: 'Indian Rupee',
  IDR: 'Indonesian Rupiah',
  THB: 'Thai Baht',
  PHP: 'Philippine Peso',
  VND: 'Vietnamese Dong',
  BDT: 'Bangladeshi Taka',
  PKR: 'Pakistani Rupee',
  LKR: 'Sri Lankan Rupee',
  NPR: 'Nepalese Rupee',
  BND: 'Brunei Dollar',
  MMK: 'Myanmar Kyat',
  KHR: 'Cambodian Riel',
  LAK: 'Laotian Kip',
  MNT: 'Mongolian Tugrik',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  SEK: 'Swedish Krona',
  NOK: 'Norwegian Krone',
  DKK: 'Danish Krone',
  NZD: 'New Zealand Dollar',
  ZAR: 'South African Rand',
  BRL: 'Brazilian Real',
  MXN: 'Mexican Peso',
  AED: 'UAE Dirham',
  SAR: 'Saudi Riyal',
  QAR: 'Qatari Riyal',
  KWD: 'Kuwaiti Dinar',
  BHD: 'Bahraini Dinar',
  OMR: 'Omani Rial',
  JOD: 'Jordanian Dinar',
  EGP: 'Egyptian Pound',
  TRY: 'Turkish Lira',
  RUB: 'Russian Ruble',
  PLN: 'Polish Zloty',
  CZK: 'Czech Koruna',
  HUF: 'Hungarian Forint',
  RON: 'Romanian Leu',
  BGN: 'Bulgarian Lev',
  HRK: 'Croatian Kuna',
  UAH: 'Ukrainian Hryvnia',
  GEL: 'Georgian Lari',
  AZN: 'Azerbaijani Manat',
  AMD: 'Armenian Dram',
  KZT: 'Kazakhstani Tenge',
  UZS: 'Uzbekistani Som',
  AFN: 'Afghan Afghani',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ILS: 'Israeli New Shekel',
  LBP: 'Lebanese Pound',
  SYP: 'Syrian Pound',
  YER: 'Yemeni Rial',
  NGN: 'Nigerian Naira',
  GHS: 'Ghanaian Cedi',
  KES: 'Kenyan Shilling',
  TZS: 'Tanzanian Shilling',
  UGX: 'Ugandan Shilling',
  ETB: 'Ethiopian Birr',
  MAD: 'Moroccan Dirham',
  DZD: 'Algerian Dinar',
  TND: 'Tunisian Dinar',
  CLP: 'Chilean Peso',
  COP: 'Colombian Peso',
  PEN: 'Peruvian Sol',
  ARS: 'Argentine Peso',
  VEF: 'Venezuelan Bolívar',
  CRC: 'Costa Rican Colón',
  GTQ: 'Guatemalan Quetzal',
  HNL: 'Honduran Lempira',
  NIO: 'Nicaraguan Córdoba',
  PAB: 'Panamanian Balboa',
  PYG: 'Paraguayan Guaraní',
  UYU: 'Uruguayan Peso',
  BOB: 'Bolivian Boliviano',
} as const;

export type CurrencyCode = keyof typeof CURRENCY_CODES;
